# Generated by Django 2.2 on 2019-05-14 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('credit_card_num', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(default='New York', max_length=255)),
                ('phone_num', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('credit_card_num', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(default='', max_length=255)),
                ('state', models.CharField(default='New York', max_length=255)),
                ('phone_num', models.PositiveIntegerField(default=0)),
                ('is_new', models.BooleanField(default=True)),
                ('is_su', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
