# Generated by Django 2.1.7 on 2019-04-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('credit_card_num', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('phone_num', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='is_su',
            field=models.BooleanField(default=False),
        ),
    ]
