# Generated by Django 2.2 on 2019-05-15 08:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessages',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 15, 8, 48, 6, 389962, tzinfo=utc)),
        ),
    ]
