# Generated by Django 2.2 on 2019-05-15 08:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190515_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessages',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 15, 8, 58, 57, 841165, tzinfo=utc)),
        ),
    ]
