# Generated by Django 2.2 on 2019-05-15 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190515_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessages',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
