# Generated by Django 2.2 on 2019-05-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='New York', max_length=255),
        ),
        migrations.AddField(
            model_name='userapplication',
            name='state',
            field=models.CharField(default='New York', max_length=255),
        ),
    ]
