# Generated by Django 2.2 on 2019-05-14 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190514_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credit_card_num',
            field=models.PositiveIntegerField(default=9999999999999999, validators=[django.core.validators.MaxLengthValidator(16), django.core.validators.MinLengthValidator(16)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_num',
            field=models.PositiveIntegerField(default=9999999999, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)]),
        ),
    ]
