# Generated by Django 2.2 on 2019-05-14 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190514_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplication',
            name='credit_card_num',
            field=models.PositiveIntegerField(default=9999999999999999, validators=[django.core.validators.MaxLengthValidator(16), django.core.validators.MinLengthValidator(16)]),
        ),
    ]
