# Generated by Django 2.2 on 2019-05-14 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190514_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_num',
            field=models.PositiveIntegerField(default=1234567890, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='credit_card_num',
            field=models.PositiveIntegerField(default=123412341234, validators=[django.core.validators.MaxLengthValidator(16), django.core.validators.MinLengthValidator(16)]),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='phone_num',
            field=models.PositiveIntegerField(default=1234567890, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)]),
        ),
    ]
