# Generated by Django 2.2 on 2019-05-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_is_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessages',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
