# Generated by Django 2.2 on 2019-05-14 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190514_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credit_card_num',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[0-9]*$'), django.core.validators.MinLengthValidator(16), django.core.validators.MaxLengthValidator(16)]),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='credit_card_num',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[0-9]*$'), django.core.validators.MinLengthValidator(16), django.core.validators.MaxLengthValidator(16)]),
        ),
    ]
