# Generated by Django 2.2 on 2019-05-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190514_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapplication',
            name='isReviewed',
            field=models.BooleanField(default=False),
        ),
    ]
