# Generated by Django 2.2 on 2019-05-15 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190514_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userblacklist',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userblacklist',
            name='user',
        ),
        migrations.AddField(
            model_name='userblacklist',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
