# Generated by Django 2.2 on 2019-05-15 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_usermessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessages',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='usermessages',
            name='title',
            field=models.CharField(default='Title', max_length=255),
        ),
    ]
