# Generated by Django 2.2 on 2019-05-13 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidPrice',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator('0.01')]),
        ),
        migrations.AlterField(
            model_name='itembidprice',
            name='startPrice',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator('0.01')]),
        ),
        migrations.AlterField(
            model_name='itemfixedprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator('0.01')]),
        ),
    ]
