# Generated by Django 2.2 on 2019-05-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20190418_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
