# Generated by Django 2.2 on 2019-05-15 05:02

import datetime
from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20190515_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='uploadDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='itembidprice',
            name='endDate',
            field=models.DateTimeField(validators=[items.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='itembidprice',
            name='startDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
