# Generated by Django 2.2 on 2019-05-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20190514_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itemapplication',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
