# Generated by Django 2.2 on 2019-05-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_blacklisted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blacklisted',
        ),
        migrations.AddField(
            model_name='item',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
