# Generated by Django 2.2 on 2019-05-12 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0006_auto_20190508_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_biddable',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_blacklisted',
        ),
        migrations.CreateModel(
            name='ItemApplication',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('key_words', models.CharField(max_length=255, null=True)),
                ('picture', models.URLField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
