# Generated by Django 2.2 on 2019-05-12 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20190512_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklist',
            old_name='seller',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='seller',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='itemapplication',
            old_name='seller',
            new_name='owner',
        ),
    ]
