# Generated by Django 2.2 on 2019-05-12 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0008_auto_20190512_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isForSale',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ItemOnMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellType', models.CharField(max_length=255)),
                ('postDate', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFixedPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.ItemOnMarket')),
            ],
        ),
        migrations.CreateModel(
            name='ItemBidPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startPrice', models.PositiveIntegerField()),
                ('duration', models.TimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.ItemOnMarket')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.ItemFixedPrice')),
            ],
            options={
                'unique_together': {('item', 'buyer')},
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.PositiveIntegerField()),
                ('bidDate', models.DateField()),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.ItemBidPrice')),
            ],
            options={
                'unique_together': {('item', 'bidder', 'bidPrice')},
            },
        ),
    ]
